version: "2"
services:
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=mydb
      volumes:
          - ./database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions